# Generated by Django 4.2 on 2023-04-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_first_name', models.CharField(max_length=50)),
                ('dentist_last_name', models.CharField(max_length=50)),
                ('dentist_age', models.IntegerField()),
                ('dentist_country', models.CharField(max_length=50)),
                ('dentist_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=50)),
                ('med_active_subst', models.CharField(max_length=50)),
                ('med_price', models.IntegerField()),
                ('med_expiration_date', models.CharField(max_length=10)),
                ('med_usage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField()),
                ('patient_country', models.CharField(max_length=50)),
                ('patient_consultation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.CharField(max_length=10)),
                ('diagnostic', models.CharField(max_length=50)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dentist')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='dent',
            field=models.ManyToManyField(through='app1.MedicationDentist', to='app1.dentist'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='med',
            field=models.ManyToManyField(through='app1.MedicationDentist', to='app1.medication'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(max_length=50)),
                ('consultation_price', models.IntegerField()),
                ('consultation_duration', models.IntegerField()),
                ('consultation_date', models.CharField(max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
    ]
